main_app/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path ('about/', views.about, name='about'),
    path('sightings/', views.SightingList.as_view(), name='index'),
    path('sightings/<int:pk>/', views.SightingDetail.as_view(), name='detail'),
    path('sightings/create/', views.SightingCreate.as_view(), name='sightings_create'),
    path('sightings/<int:pk>/update', views.SightingUpdate.as_view(), name='sightings_update'),
    path('sightings/<int:pk>/delete', views.SightingDelete.as_view(), name='sightings_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('sightings/<int:pk>/add_comment/', views.add_comment, name='add_comment'),
    path('sightings/<int:pk>/<int:comment_id>/', views.comments_update, name='comments_update'),
    path('sightings/<int:sighting_id>/<int:comment_id>/comments_delete/', views.comments_delete, name='comments_delete'),
    path('sightings/<int:sighting_id>/<int:comment_id>/<int:reply_id>/replies_delete/', views.replies_delete, name='replies_delete'),
    path('sightings/<int:sighting_id>/<int:comment_id>/add_reply', views.add_reply, name='add_reply'),
    path('likecomment/<int:pk>/<int:comment_id>/', views.like_comment, name='like_comment'),
    path('sightings/<int:sighting_id>/add_photo/', views.add_photo, name='add_photo'),
    path('sightings/<int:sighting_id>/<int:photo_id>/photos_delete/', views.photos_delete, name='photos_delete'),
    path('map/', views.map, name='map'),
    path('generate/', views.generate, name='generate'),
    path('likes/<int:pk>/', views.like_sighting, name='like_sighting'),
]

whalescope/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.urls import reverse

WHALE_SPECIES = (
    ('1', 'Select Species'),
    ('2', 'Orca'),
    ('3', 'Minke'),
    ('4', 'Humpback'),
    ('5', 'Blue'),
    ('6', 'Sperm'),
    ('7', 'Beluga'),
    ('8', 'Gray'),
    ('9', 'Fin'),
    ('10', 'Dolphin'),
    ('11', 'Seal'),
    ('12', 'Sea Lion'),
    ('13', 'Sea Otter'),
    ('14', 'Other'),
    ('15', 'Unknown')
)
class Sighting(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField('sighting date')
    latitude = models.DecimalField(max_digits=12, decimal_places=9)
    longitude = models.DecimalField(max_digits=12, decimal_places=9)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    species = models.CharField(
        max_length=2,
        choices=WHALE_SPECIES,
        default=WHALE_SPECIES[0][0]
    )
    likes = models.ManyToManyField(User, related_name='sighting_likes', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id})

    def has_comments(self):
        return self.comment_set

    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    text = models.TextField('comment', max_length=1000)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    sighting = models.ForeignKey(Sighting, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)

    def __str__(self):
        return str(self.text)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id})

    def has_likes(self):
        return self.likes.count()

    def has_replies(self):
        return self.reply.count()

    class Meta:
        ordering = ['-created_date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    sighting = models.ForeignKey(Sighting, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for sighting_id: {self.sighting_id} @{self.url}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Profile of user {self.user.username}"

class Reply(models.Model):
    text = models.TextField('comment', max_length=1000)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.text)

main_app/forms.py
from django.forms import ModelForm
from django.db import models
from .models import Comment, Reply

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['text']

main_app/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import *
from .forms import *
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
import os
import json
import environ
from django.conf import settings
import requests
from django.http import HttpResponse

# constants for AWS S3 photos
S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'whalescope'

# Create views below:
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def add_photo(request, sighting_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, sighting_id=sighting_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', pk=sighting_id)

class SightingList(LoginRequiredMixin, ListView):
    model = Sighting

class SightingDetail(LoginRequiredMixin, DetailView):
    model = Sighting
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        liked = get_object_or_404(Sighting, id=self.kwargs['pk'])
        total_likes = liked.total_likes()
        liked_it = False
        if liked.likes.filter(id=self.request.user.id).exists():
            liked_it = True

        context['comment_form'] = CommentForm()
        context['reply_form'] = ReplyForm()
        context['total_likes'] = total_likes
        context['liked_it'] = liked_it
        
        return context

class SightingCreate(LoginRequiredMixin, CreateView):
    model = Sighting
    fields = ['title', 'date', 'latitude', 'longitude', 'location', 'description', 'species']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['GOOGLE_API_KEY'] = settings.GOOGLE_API_KEY
        return context

class SightingUpdate(LoginRequiredMixin, UpdateView):
    model = Sighting
    fields = ['date', 'latitude', 'longitude', 'location', 'description', 'species']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['GOOGLE_API_KEY'] = settings.GOOGLE_API_KEY
        return context

class SightingDelete(LoginRequiredMixin, DeleteView):
    model = Sighting
    success_url = '/sightings/'


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('index')
    else:
        error_message = 'Invalid sign up - try again'
        
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


@login_required
def profile(request):
    sighting = Sighting.objects.filter(user=request.user)
    return render(request, 'registration/user_profile.html', {'sightings': sighting})

@login_required
def add_comment(request, pk):
    sighting = get_object_or_404(Sighting, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.sighting = sighting
            form.save()
            return redirect('detail', pk=sighting.pk)
        
    else:
        form = CommentForm()
    return render(request, 'detail', {'form': form})

@login_required
def comments_update(request, pk, comment_id):
    sighting = get_object_or_404(Sighting, pk=pk)
    if request.method == 'POST':
        if comment_id:
            form = CommentForm(instance=Comment.objects.get(id=comment_id), data=request.POST)
            form.save()
            return redirect('detail', pk=sighting.pk)
        else:
            form = CommentForm(data=request.POST)
        return redirect('detail', pk=sighting.pk)

@login_required
def comments_delete(request, sighting_id, comment_id):
    context={}
    obj = get_object_or_404(Comment, id=comment_id)

    if request.method == 'GET':
        obj.delete()
        return redirect('detail', sighting_id)

@login_required
def photos_delete(request, sighting_id, photo_id):
    context={}
    obj = get_object_or_404(Photo, id=photo_id)

    if request.method == 'GET':
        obj.delete()
        return redirect('detail', sighting_id)

@login_required
def map(request):
    user_sightings = Sighting.objects.all()
    sighting_list = []

    for s in user_sightings:
        s_photo = Photo.objects.filter(sighting_id=s.id).first()
        
        if s_photo == None:
            s_url = "https://i.imgur.com/QLa6Vjy.png"
        else:
            s_url = s_photo.url

        new_sighting = {
            'id': s.id,
            'title': s.title,
            'species': s.species,
            'lat': str(s.latitude),
            'lng': str(s.longitude),
            'url': str(s_url)
        }
        sighting_list.append(new_sighting)

    return render(request, 'main_app/sighting_map.html', {
        'sightings': json.dumps(sighting_list),
        'GOOGLE_API_KEY': settings.GOOGLE_API_KEY
    })


@login_required
def like_sighting(request, pk):
    sighting = get_object_or_404(Sighting, pk=pk)
    liked_it = False
    if sighting.likes.filter(id=request.user.id).exists():
        sighting.likes.remove(request.user)
        liked_it = False
    else:
        sighting.likes.add(request.user)
        liked_it = True
    return HttpResponseRedirect(reverse('detail', args=[str(pk)]))

def generate(request):
    lat = json.loads(request.body.decode('utf-8')).get('lat')
    lng = json.loads(request.body.decode('utf-8')).get('lng')
    rootURL = "http://hotline.whalemuseum.org/"
    searchURL = "api.json?near=" + lat + "," + lng + "&radius=3"
    newURL = rootURL + searchURL
    print('Running search...')
    try:
        r = requests.get(newURL).json()
        return HttpResponse(json.dumps(r), content_type="application/json")
    except: 
        pass


@login_required
def add_reply(request, sighting_id, comment_id):
    sighting = get_object_or_404(Sighting, id=sighting_id)
    comment = get_object_or_404(Comment, id=comment_id)
    
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.comment = comment
            form.save()
            return redirect('detail', sighting_id)
        
    else:
        form = ReplyForm()
    return render(request, 'detail', {'form': form})

@login_required
def replies_delete(request, sighting_id, comment_id, reply_id):
    context={}
    obj = get_object_or_404(Reply, id=reply_id)

    if request.method == 'GET':
        obj.delete()
        return redirect('detail', sighting_id)


@login_required
def like_comment(request, pk, comment_id):
    sighting = get_object_or_404(Sighting, pk=pk)
    if request.method == 'POST':
        if comment_id:
            comment = get_object_or_404(Comment, id=comment_id)
            like = False
            if comment.likes.filter(id=request.user.id).exists():
                comment.likes.remove(request.user)
                like = False
            else:
                comment.likes.add(request.user)
                like = True
    return HttpResponseRedirect(reverse('detail', args=[str(pk)]))

main_app/templates/main_app/sighting_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1 class="delete-header">Delete Sighting</h1>

<h4 class="conf-txt">Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete!" class="delete-btn">
    <a class="cancel-delete" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/sighting_detail.html
{% extends 'base.html' %}
{% block content %}


<h1>Sighting Details</h1>
<div class="sighting-container">  
    <div class="card-detail">
        <span class="card-title-detail">{{ object.title.capitalize }}</span>
        <p>Species: {{ object.get_species_display }}</p>
        <p>{{ object.description }}</p>
        <p>{{ object.date }}</p>
        <p>Latitude: {{ object.latitude }}</p>
        <p>Longitude: {{ object.longitude }}</p>
        <p>Location: {{ object.location }}</p>
        {% if user == sighting.user %}
            <a href="{% url 'sightings_update' object.id %}" class="edit-btn">Edit</a>
            <a href="{% url 'sightings_delete' object.id %}" class="delete-btn">Delete</a> 
        {% endif %}
             <form class="like-btn" action="{% url 'like_sighting' object.id %}" method="post">
                {% csrf_token %} 
                <button type="submit" name="sighting_id" style="background-color:transparent; border: none;">
                    {% if liked_it %}
                    <i style="color: #C0FDFF" class='material-icons likes'>thumb_up</i>
                    {% else %}
                    <i style="color: grey" class='material-icons likes'>thumb_up</i>
                    {% endif %}
                    {% if total_likes %}
                    <p style="margin-top: 0;" class="like-text"><small>{{ total_likes }} Likes</small></p>
                    {% else %}
                    {% endif %} 
                </button>
            </form>
            
            <form action="{% url 'add_comment' object.id %}" method="post">
                {% csrf_token %}
                <textarea name="text" class="comment-input" placeholder="Write a Comment" cols="40" rows="10" maxlength="1000" required="" id="id_text"></textarea>
                <input type="submit" class="photo-upload-btn" value="Add Comment" class="btn">
            </form>

{% if sighting.has_comments.count %}
<h4>{{object.title.capitalize }} has {{ sighting.has_comments.count }} comment{{ sighting.has_comments.count|pluralize }}</h4>
    {% for comment in sighting.comment_set.all %}
            
        <div>
            <div class="comment-container">
                <div style="display: inline-flex;">{{ comment.text }}</div>
                <div class="right" style = "text-transform:capitalize;" style="display: inline-flex; color: white;"><small>By {{ comment.user }}</small></div>
                <div class="left" ><small>{{ comment.created_date }}</small></div>
                <button  class="reply_button" id="reply_button_{{ comment.id }}" style=" background-color: transparent; border: none;">reply</button>
                {% if user == comment.user %}
                <button class="edit_button" id="edit_button_{{ comment.id }}">Edit</button>
                <a class="delete-comment" href="{% url 'comments_delete' sighting.id comment.id %}">Delete</a>
                {% endif %}
                <form action="{% url 'like_comment' sighting.id comment.id %}"  class="like-btn" method="post">
                    {% csrf_token %} 
                    <button type="submit" name="comment_id" style="background-color:transparent; border: none;">
                        {% if user in comment.likes.all %} 
                        <i style="color: #C0FDFF; border: none;" class='material-icons likes'>thumb_up</i>
                        {% else %}
                        <i style="color: lightgrey; border: none;" class='material-icons likes'>thumb_up</i>
                        {% endif %}
                        {% if comment.has_likes %}
                        <p style="margin-top: 0; color: white"><small>{{ comment.has_likes }} Like{{ comment.likes.count|pluralize }}</small></p>
                        {% else %}
                        {% endif %} 
                    </button>
                </form>

            </div>
                                            
            <div class="left-align reply_form"  id="reply_form_{{ comment.id }}">
                <form action="{% url 'add_reply' sighting.id comment.id %}" method="post">
                    {% csrf_token %}
                    <textarea placeholder="Write a Reply" class="comment-input"name="text" cols="40" rows="10" maxlength="1000" required="" id="id_text"></textarea>
                    <input type="submit" class="photo-upload-btn" value="Add Reply" class="btn">
                </form>
            </div>
                    
            {% for reply in comment.reply_set.all %}
            <div class="reply-containter">
                <div style="display: inline-flex; color: white">{{ reply.text }}</div><br/>
                <div  style="display: inline-flex; color: white;">  By {{ reply.user }}</div>
                {% if user == reply.user %}
                <a class="delete-comment" href="{% url 'replies_delete' sighting.id comment.id reply.id %}">Delete</a>
                {% endif %}
                {% endfor %}   
            </div>
                <div id="edit_field_{{ comment.id }}" class="edit_field">
                    <form  action="{% url 'comments_update' object.id comment.id %}" method="post">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                        <input type="submit" value="Edit Comment">
                    </form>
                </div>
                {% endfor %}
                {% else %}
        <div>
            No Comments Yet
        </div>
    {% endif %} 
</div>

<div class="card-detail">
    {% for photo in sighting.photo_set.all %}
    <img class="whale-photo" src="{{photo.url}}">
    <br>
        {% if user == sighting.user %}
            <a href="{% url 'photos_delete' sighting.id photo.id %}" class="delete-btn">Delete</a>
        {% endif %}
    {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        <img src="https://i.imgur.com/AzyIR4f.png" alt="WhaleScope Logo">
    {% endfor %}
    {% if user == sighting.user %}
    <form action="{% url 'add_photo' object.id %}" enctype="multipart/form-data" method="post" class="card-panel">
        {% csrf_token %}
        <input type="file"  name="photo-file">
        <input type="submit" class="photo-upload-btn" value="Upload Photo" class="btn">
    </form>
    {% endif %} 
</div>
{% endblock %}

main_app/templates/main_app/sighting_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.title }}</span> </h1>
{% else %}
    <h1>Add Sighting</h1>
{% endif %}

<p>Fill in the input fields below with a title, date, and description for your whale sighting. Make sure to select a species!<br/>And don't stress out about the latitude and longitude. We got you!<br/>Just click on the map below wherever your whale sighting occurrred and the input fields will automatically populate with the correct coordinates.<br/>Double check that you like the location name and then click that 'Submit' button to add another dope scope to your collection. Gnarly!</p>
<div class="sighting-container">
<form action="" class="sighting-form" method="post">
    <h2>Add Your Sighting</h2>
    {% csrf_token  %}        
        <input class="sighting-input"  placeholder="Title"type="text" name="title" maxlength="100" required="" id="id_title">
        <input class="sighting-input" placeholder="Latitude" type="number" name="latitude" step="1e-9" required="" id="id_latitude"> 
        <input class="sighting-input" placeholder="Longitude" type="number" name="longitude" step="1e-9" required="" id="id_longitude"> 
        <input  class="sighting-input" placeholder="Location" type="text" name="location" maxlength="100" required="" id="id_location"> 
        <textarea class= "sighting-description" placeholder="Sighting Description (max length 500 characters)" name="description" cols="40" rows="10" maxlength="500" required="" id="id_description"></textarea>
        <input placeholder="Sighting Date" class="date-picker" type="date" name="date" required="" id="id_date">

        <select name="species" class="select-species" id="id_species">
            <option value="1">Select Species</option>
            <option value="2">Orca</option>
            <option value="3">Minke</option>
            <option value="4">Humpback</option>
            <option value="5">Blue</option>
            <option value="6">Sperm</option>
            <option value="7">Beluga</option>
            <option value="8">Gray</option>
            <option value="9">Fin</option>
            <option value="10">Dolphin</option>
            <option value="11">Seal</option>
            <option value="12">Sea Lion</option>
            <option value="13">Sea Otter</option>
            <option value="14">Other</option>
            <option value="15">Unknown</option>
        </select><br/>
            <input class="login-submit" type="submit" value="Submit!" class="btn">
</form>
<form action="" class="map-container">
    <h3>Click the map for latitude & longitude:</h3>
<style>
    #map {
        height:400px;
        width:600px;
        margin-right: 33%;
    }
</style>

    <div>
        <input id="address" class="location-input" type="textbox" onfocus="this.value=''" value="Enter Your Location" />
        <input id="submit" class="location-submit"  type ="button" value="Search" />
    </div>
    <div id="map"></div>

</form>
</div>

<script>
    let map, infoWindowLatLng, geocoder;
    let myLatLng = {lat:41.498628,lng:-81.702427}
    function initMap() {
        var options = {
            zoom: 8,
            center: myLatLng
        };
        
        map = new google.maps.Map(document.getElementById('map'), options);
        infoWindow = new google.maps.InfoWindow();
        geocoder = new google.maps.Geocoder();
        infoWindowLatLng = new google.maps.InfoWindow(
            {content: "Click the map to get Lat/Lng!", position: myLatLng}
        );
        infoWindowLatLng.open(map);      
        map.addListener('click', function(event) {
            infoWindowLatLng.close()
            infoWindowLatLng = new google.maps.InfoWindow({position: event.latLng});
            var latLngStr = event.latLng.toString()
            infoWindowLatLng.setContent(latLngStr);
            infoWindowLatLng.open(map);
            newLaLn = latLngStr.replace('(','').replace(')','')
            arrLaLn = newLaLn.split(',')
            sLat = parseFloat(arrLaLn[0]).toFixed(9)
            sLng = parseFloat(arrLaLn[1]).toFixed(9)
            document.getElementById("id_latitude").value = sLat
            document.getElementById("id_longitude").value = sLng
    
            geocoder.geocode({
                'latLng': event.latLng
                }, 
                function(results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        var addStr = results[0].formatted_address;
                        document.getElementById("id_location").value = addStr;
                    }
                }
            });
        });
    }
    
    findGeoLoc();
    
    document.getElementById("submit").addEventListener("click", () => {
        geocodeAddress(geocoder, map);
    });
    
    document.getElementById("address").addEventListener("keyup", function(event) {
        if (event.keyCode === 13) {
            event.preventDefault();
            document.getElementById("submit").click();
        }
    });

    function findGeoLoc() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                position => {
                    const myLatLng = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    infoWindow.setPosition(myLatLng);
                    infoWindow.setContent("Location found. Click the map to get Lat/Lng!");
                    infoWindow.open(map)
                    map.setCenter(myLatLng);
                },
                () => {
                    handleLocationError(true, infowWindow, map.getCenter());
                }
            );
        } else {
            handleLocationError(false, infoWindow, map.getCenter());
        }
    }

    function geocodeAddress(geocoder, resultsMap) {
        const address = document.getElementById("address").value;
        geocoder.geocode({ address: address }, ( results, status ) => {
            if (status === "OK") {
                resultsMap.setCenter(results[0].geometry.location);
            } else {
                alert("Geocode was not successful for the following reason: " + status);
            }
        });
    }
</script>
<script defer
    src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&callback=initMap">
</script>


{% endblock %}

main_app/templates/main_app/sighting_list.html
{% extends 'base.html' %}
{% block content %}
<style>
  * {
    box-sizing: border-box;
  }
  main {
    margin: 5rem;
  }
</style>

<h1 style="font-size: 50px;">Whale Feed</h1>

{% for object in object_list %}
  <div class="row">
    <div class="column">
    <div class="card">
      {% for photo in object.photo_set.all %}
      {% if forloop.first %}
        <a href="{% url 'detail' object.id %}"><img src="{{photo.url}}" alt="Whale Photo" style="width:100%; height: 15rem;"></a>
        {% endif %}
        {% empty %}
        <a href="{% url 'detail' object.id %}"><img src="https://i.imgur.com/AzyIR4f.png" style="width:100%; height: 15rem;" alt="Whale Photo" style="width:100%;"></a>
        {% endfor %}
            <p style = "text-transform:capitalize;" class="card-title">{{ object.title }}</p> 
            <p style ="text-transform:capitalize;">Posted by: {{ object.user }}</p>
            <p>Location: {{ object.location }}</p>
            <p>Species: {{ object.get_species_display }}</p>
            <p><small>{{ object.has_comments.count }} comment{{ object.has_comments.count|pluralize }}</small></p>
            <p>{{ object.date }}</p>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}